# Generated by Django 6.0.3 on 2026-03-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
