# Generated by Django 6.0.3 on 2026-04-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_favorite_id_alter_favorite_user"),
        ("store", "0009_remove_order_created_at_order_address_order_city_and_more"),
    ]

    operations = []
